//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Test2.Data_Mvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_Entry
    {
        public int Id { get; set; }
        public string Emp_Name { get; set; }
        public string Emp_Email { get; set; }
        public int Emp_Salary { get; set; }
        public string Emp_Id { get; set; }
    }
}
